### ISSUE TITLE
请问该项目是基于python哪个版本呢

### ISSUE THREAD

**Issue by qq985382384** [yuban10703/IOTQQ-color_pic#1]

**Comment by yuban10703** [comment]
py3.8

**Comment by yuban10703** [comment]
那个正则那里用了个3.8的新语法 改一下就好了。。。

**Comment by qq985382384** [comment]
项目运行需要依赖于IOTQQ本体吧，尴尬的是我并不会改，我现在换了py3.8，遗憾的是现在卡在了依赖包上

**Comment by yuban10703** [comment]
哪个依赖出问题了?......

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/83003711-46d67680-a041-11ea-817a-9776f0b1f4a5.png)
你把337和338的注释去掉,然后把339注释掉,就可以用旧版本py了

**Comment by yuban10703** [comment]
等我改一下吧......

**Comment by yuban10703** [comment]
好了,把3.8的新语法改回去了

**Comment by qq985382384** [comment]
万分感谢，可以跑起来了
![D1$B6_FETYU2KG F6BACQ@A](https://user-images.githubusercontent.com/53076564/83007040-a9ca0c80-a045-11ea-9937-54b3bd5ebf74.png)

**Comment by yuban10703** [comment]
嗯嗯

**Comment by githubdl** [comment]
请问我出现
![image](https://user-images.githubusercontent.com/29683723/85502054-25a17f80-b619-11ea-99cf-fe5efc9b8b39.png)
这样的情况，应该怎么解决呢？

**Comment by yuban10703** [comment]
> 请问我出现
> ![image](https://user-images.githubusercontent.com/29683723/85502054-25a17f80-b619-11ea-99cf-fe5efc9b8b39.png)
> 这样的情况，应该怎么解决呢？

啊？..

**Comment by yuban10703** [comment]
> 请问我出现
> ![image](https://user-images.githubusercontent.com/29683723/85502054-25a17f80-b619-11ea-99cf-fe5efc9b8b39.png)
> 这样的情况，应该怎么解决呢？

你config怎么填的？

**Comment by githubdl** [comment]
> > 请问我出现
> > ![image](https://user-images.githubusercontent.com/29683723/85502054-25a17f80-b619-11ea-99cf-fe5efc9b8b39.png)
> > 这样的情况，应该怎么解决呢？
> 
> 你config怎么填的？

![image](https://user-images.githubusercontent.com/29683723/85846941-37318580-b7d9-11ea-8670-880201a98827.png)
这样的

**Comment by githubdl** [comment]
> > 请问我出现
> > ![image](https://user-images.githubusercontent.com/29683723/85502054-25a17f80-b619-11ea-99cf-fe5efc9b8b39.png)
> > 这样的情况，应该怎么解决呢？
> 
> 你config怎么填的？

{
  "color_pickey": "",
  "send_pic_original": false,
  "webapi": "http://127.0.0.1:8888",
  "botqqs": [1426285228],
  "blacklist": [],
  "whitelist": [],
  "r18_whitelist": [],
  "r18_only_whitelist": [1005096441],
  "setu_pattern": "来(.*?)[点丶份张](.*?)的?[色瑟涩]图",
  "path": "Y:\\PICS\\",
  "setu_threshold": 5,
  "RevokeMsg": true,
  "RevokeMsg_time": 10,
  "threshold_to_send": "要这么多色图你怎么不冲死呢?",
  "notfound_to_send": "淦 你的xp好奇怪啊",
  "wrong_input_to_send": "必须是正整数数字哦",
  "before_nmsl_to_send" : "酝酿ing",
  "before_setu_to_send" : "发送ing" 
}

**Comment by yuban10703** [comment]
> > > 请问我出现
> > > ![image](https://user-images.githubusercontent.com/29683723/85502054-25a17f80-b619-11ea-99cf-fe5efc9b8b39.png)
> > > 这样的情况，应该怎么解决呢？
> > 
> > 
> > 你config怎么填的？
> 
> {
> "color_pickey": "",
> "send_pic_original": false,
> "webapi": "http://127.0.0.1:8888",
> "botqqs": [1426285228],
> "blacklist": [],
> "whitelist": [],
> "r18_whitelist": [],
> "r18_only_whitelist": [1005096441],
> "setu_pattern": "来(.*?)[点丶份张](.*?)的?[色瑟涩]图",
> "path": "Y:\PICS\",
> "setu_threshold": 5,
> "RevokeMsg": true,
> "RevokeMsg_time": 10,
> "threshold_to_send": "要这么多色图你怎么不冲死呢?",
> "notfound_to_send": "淦 你的xp好奇怪啊",
> "wrong_input_to_send": "必须是正整数数字哦",
> "before_nmsl_to_send" : "酝酿ing",
> "before_setu_to_send" : "发送ing"
> }

换新版本试试
还有
![image](https://user-images.githubusercontent.com/39484884/85847233-9f806700-b7d9-11ea-8512-d6edbf82dbed.png)

**Comment by yuban10703** [comment]
> "path": "Y:\PICS\",

path要本地有图才填

**Comment by githubdl** [comment]
> > > > 请问我出现
> > > > ![image](https://user-images.githubusercontent.com/29683723/85502054-25a17f80-b619-11ea-99cf-fe5efc9b8b39.png)
> > > > 这样的情况，应该怎么解决呢？
> > > 
> > > 
> > > 你config怎么填的？
> > 
> > 
> > {
> > "color_pickey": "",
> > "send_pic_original": false,
> > "webapi": "http://127.0.0.1:8888",
> > "botqqs": [1426285228],
> > "blacklist": [],
> > "whitelist": [],
> > "r18_whitelist": [],
> > "r18_only_whitelist": [1005096441],
> > "setu_pattern": "来(.*?)[点丶份张](.*?)的?[色瑟涩]图",
> > "path": "Y:\PICS",
> > "setu_threshold": 5,
> > "RevokeMsg": true,
> > "RevokeMsg_time": 10,
> > "threshold_to_send": "要这么多色图你怎么不冲死呢?",
> > "notfound_to_send": "淦 你的xp好奇怪啊",
> > "wrong_input_to_send": "必须是正整数数字哦",
> > "before_nmsl_to_send" : "酝酿ing",
> > "before_setu_to_send" : "发送ing"
> > }
> 
> 换新版本试试
> 还有
> ![image](https://user-images.githubusercontent.com/39484884/85847233-9f806700-b7d9-11ea-8512-d6edbf82dbed.png)

好的，我去试一试，谢谢大佬的答复

**Comment by githubdl** [comment]
> > "path": "Y:\PICS",
> 
> path要本地有图才填

这个可以调用本地图片吗？

**Comment by yuban10703** [comment]
> > > "path": "Y:\PICS",
> > 
> > 
> > path要本地有图才填
> 
> 这个可以调用本地图片吗？

只对我的api有效,要本地有图才行,没图空着就行

**Comment by githubdl** [comment]
> > > > "path": "Y:\PICS",
> > > 
> > > 
> > > path要本地有图才填
> > 
> > 
> > 这个可以调用本地图片吗？
> 
> 只对我的api有效,要本地有图才行,没图空着就行

好的，刚刚修改了一下配置文件，把path留空，然后添加了白名单，就解决了问题。（应该就是白名单的问题）

**Comment by yuban10703** [comment]
> > > > > "path": "Y:\PICS",
> > > > 
> > > > 
> > > > path要本地有图才填
> > > 
> > > 
> > > 这个可以调用本地图片吗？
> > 
> > 
> > 只对我的api有效,要本地有图才行,没图空着就行
> 
> 好的，刚刚修改了一下配置文件，把path留空，然后添加了白名单，就解决了问题。（应该就是白名单的问题）

嗯..
