### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by MapleNe** [yuban10703/IOTQQ-color_pic#10]
希望作者把搜图的功能完善一下
添加一个yande的api，两个api的图太少了 有的搜出来是重复的
.开启色图 使用之后有返回信息 group not in blacklist 但是就是无法使用

**Comment by yuban10703** [comment]
开启色图不能用的话  看一下后台log是什么

**Comment by yuban10703** [comment]
yande是搜图的么?

**Comment by MapleNe** [comment]
> yande是搜图的么?
yande不是搜图 是图站

**Comment by MapleNe** [comment]
> 开启色图不能用的话 看一下后台log是什么

我看看

**Comment by yuban10703** [comment]
emm,yande的api在哪....

**Comment by MapleNe** [comment]
> emm,yande的api在哪....

yande.re/help/api
yande.re/post.json

**Comment by MapleNe** [comment]
后台没有错误log

**Comment by yuban10703** [comment]
> 后台没有错误log

有log输出么...
看看你的config.json

**Comment by MapleNe** [comment]
> > 后台没有错误log
> 
> 有log输出么...
> 看看你的config.json
![9]M~7[GUXTQI_K4J0P%FO1H.png](https://i.loli.net/2020/07/31/BPRJuws6IiMtD1H.png)

**Comment by MapleNe** [comment]
https://i.loli.net/2020/07/31/CSjH436BikZ2MtE.png

**Comment by yuban10703** [comment]
你开白名单了啊

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/88998779-66ca3500-d325-11ea-8948-72c857469f20.png)

**Comment by MapleNe** [comment]
我删除看看

**Comment by MapleNe** [comment]
可以了 等老哥把那个yande.re的图站搞好

**Comment by yuban10703** [comment]
yande.re的tag貌似只能搜英文的样子?....

**Comment by MapleNe** [comment]
> yande.re的tag貌似只能搜英文的样子?....

https://yande.re/post.json?limit=1
这个是限制输出一个

**Comment by MapleNe** [comment]
> yande.re的tag貌似只能搜英文的样子?....

貌似是这样

**Comment by MapleNe** [comment]
> > yande.re的tag貌似只能搜英文的样子?....
> 
> 貌似是这样

只是随机图片的话倒不是用来搜图 只是指定的话就只能用英文了，搜图用那个ascii2d

**Comment by yuban10703** [comment]
emm,有空加上

**Comment by MapleNe** [comment]
啊这
图片消息执行状态:[Ret:('未知错误:', TypeError("'NoneType' object is not subscriptable",))]

图片消息执行状态:[Ret:超时~]

**Comment by yuban10703** [comment]
> 啊这
> 图片消息执行状态:[Ret:('未知错误:', TypeError("'NoneType' object is not subscriptable",))]
> 
> 图片消息执行状态:[Ret:超时~]

超时可能是你上传速度太慢了

**Comment by yuban10703** [comment]
emm,你刚刚调用了啥呀

**Comment by MapleNe** [comment]
也许要换服务器了，没调用啥 只是发色图而已

**Comment by yuban10703** [comment]
yande.re的返回貌似不是随机的鸭....

**Comment by MapleNe** [comment]
可以随机，参数我忘了，我找找

**Comment by MapleNe** [comment]
> yande.re的返回貌似不是随机的鸭....

https://yande.re/post.json?order:ramdon
这个是随机的，不过没有限制输出，你自己加个参数吧

**Comment by yuban10703** [comment]
soka

**Comment by MapleNe** [comment]
> soka

加完叫我昂

**Comment by yuban10703** [comment]
emm,可能要两天吧

**Comment by MapleNe** [comment]
> emm,可能要两天吧

啊这。。

**Comment by yuban10703** [comment]
> > yande.re的返回貌似不是随机的鸭....
> 
> https://yande.re/post.json?order:ramdon
> 这个是随机的，不过没有限制输出，你自己加个参数吧

这个也不是随机鸭

**Comment by yuban10703** [comment]
是这样么?...
https://yande.re/post.json?limit=1&order=ramdon

**Comment by MapleNe** [comment]
加油
