### ISSUE TITLE
色图api

### ISSUE THREAD

**Issue by MapleNe** [yuban10703/IOTQQ-color_pic#12]
HTTPConnectionPool(host='api.yuban10703.xyz', port=2333): Max retries exceeded with url: /setu_v3?type=1&num=1&tag= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbbbe200048>: Failed to establish a new connection: [Errno 111] Connection refused',))
你api无了？

**Comment by yuban10703** [comment]
问题不大，晚点恢复

**Comment by MapleNe** [comment]
> 问题不大，晚点恢复

整快点，要用

**Comment by MapleNe** [comment]
能兼容python2.7吗？
 路由器装不了3

**Comment by yuban10703** [comment]
不能
